name: CI Bomberman Arena

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Client - Install, Lint & Test
        working-directory: ./client
        run: |
          npm install
          chmod +x node_modules/.bin/*
          npm run lint
          npm run test -- --passWithNoTests

      - name: Serveur - Install, Lint & Test
        working-directory: ./server
        run: |
          npm install
          chmod +x node_modules/.bin/*
          npm run lint
          npm run test -- --passWithNoTests